version: '3'
services:
  remarkabot:
    build: .
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=your_token_here
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    volumes:
      - ./gpt:/gpt

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongoremarkabot:/data/db

volumes:
  mongoremarkabot:
